car/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('car/', views.car, name="car"),
]

car_book/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('car.urls')),
    path('', include('car_details.urls')),
    path('', include('home.urls')),
    path('', include('reservation.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservation/urls.py
from django.urls import path
from .views import ReserveView, BookingList

urlpatterns = [
    path('car/<int:id>/reservation/', ReserveView.as_view(), name="reservation"),
    path('booking_list/', BookingList.as_view(), name="BookingListView"),
]

reservation/models.py
from django.db import models

# Create your models here.

reservation/forms.py
from django import forms


class AvailabilityForm(forms.Form):
    location = forms.CharField(max_length=256)
    pickup_date = forms.DateTimeField(required=True, input_formats=["%Y-%m-%dT%H:%M"])
    return_date = forms.DateTimeField(required=True, input_formats=["%Y-%m-%dT%H:%M"])

reservation/views.py
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, HttpResponse
from django.utils.decorators import method_decorator
from django.views.generic import ListView, FormView, View
from car_models.models import Car, Booking
from .forms import AvailabilityForm
from reservation.booking_functions.availability import check_availability

# Create your views here.

class ReserveView(View):
    def get(self, request, *args, **kwargs):
        car_id = self.kwargs.get('id', None)
        form = AvailabilityForm
        car_list = Car.objects.filter(id=car_id)
        if len(car_list) > 0:
            car = car_list[0]
            context = {
                'car': car,
                'car_id': car.id,
                'car_brand': car.brand,
                'car_model': car.car_model,
                'car_transmission': car.transmission,
                'car_seats':car.seats,
                'car_type':car.type,
                'car_fuel': car.fuel,
                'car_rent_price':car.rent_price,
                'form': form,
            }
            return render(request, 'availability_form.html', context)
        else:
            return HttpResponse('Searching wrong')

    @method_decorator(login_required(login_url='login'))
    def post(self, request, *args, **kwargs):
        car_id = self.kwargs.get('id', None)
        car = Car.objects.filter(id=car_id).first()
        if not car:
            return HttpResponse('Vehicle not found in database!.')

        form = AvailabilityForm(request.POST)
        if not form.is_valid():
            return HttpResponse('Form is not valid!.')

        data = form.cleaned_data

        if data['pickup_date'] > data['return_date']:
            return HttpResponse('Pickup date can not be greater than return date!.')

        if data['pickup_date'].timestamp() < datetime.today().timestamp():
            return HttpResponse('Pickup date can not be in the past!.')

        if not check_availability(car, data['pickup_date'], data['return_date']):
            return HttpResponse('This vehicle is booked for selected dates!.')

        booking = Booking.objects.create(
            car_customer=self.request.user,
            car=car,
            pickup_location=data['location'],
            pickup_date=data['pickup_date'],
            return_date=data['return_date'],
        )
        booking.save()
        return HttpResponse(booking)


class BookingList(ListView):
    model = Booking
    def get_queryset(self):
        booking_list= Booking.objects.filter(car_customer=self.request.user)
        return booking_list

reservation/templates/availability_form.html
<!DOCTYPE html>
<html lang="en">

	<head>

		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta http-equiv="x-ua-compatible" content="ie=edge">

		<title>Reservation - Rotors - Car Rental HTML5 Template</title>

        {% extends 'base.html' %}

        {% load static %}

	</head>

	<body>

    {% block content %}

		<!-- main body - start
		================================================== -->
		<main>


			<!-- breadcrumb_section - start
			================================================== -->
			<section class="breadcrumb_section text-center clearfix">
				<div class="page_title_area has_overlay d-flex align-items-center clearfix" data-bg-image="assets/images/breadcrumb/bg_03.jpg">
					<div class="overlay"></div>
					<div class="container" data-aos="fade-up" data-aos-delay="100">
						<h1 class="page_title text-white mb-0">Reservation</h1>
					</div>
				</div>
				<div class="breadcrumb_nav clearfix" data-bg-color="#F2F2F2">
					<div class="container">
						<ul class="ul_li clearfix">
							<li><a href="{% url 'home' %}">Home</a></li>
							<li><a href="{% url 'car' %}">Our Cars</a></li>
							<li>Reservation</li>
						</ul>
					</div>
				</div>
			</section>
			<!-- breadcrumb_section - end
			================================================== -->


			<!-- reservation_section - start
			================================================== -->
			<section class="reservation_section sec_ptb_100 clearfix">
				<div class="container">
					<div class="row justify-content-lg-between justify-content-md-center justify-content-sm-center">

						<div class="col-lg-4 col-md-8 col-sm-10 col-xs-12">
							<div class="feature_vehicle_item mt-0 ml-0" data-aos="fade-up" data-aos-delay="100">
								<h3 class="item_title mb-0">
									<a href="#!">
										{{ car_brand }} {{ car_model }}
									</a>
								</h3>
								<div class="item_image position-relative">
									<a class="image_wrap" href="#!">
										<img src="{{MEDIA_URL}}{{car.images.first.image_url}}" alt="image_not_found">
									</a>
									<span class="item_price bg_default_blue">${{ car_rent_price }}/Day</span>
								</div>
								<ul class="info_list ul_li_center clearfix">
									<li>{{ car_type }}</li>
									<li>{{ car_transmission }}</li>
									<li>{{ car_seats }} Seats</li>
									<li>{{ car_fuel }}</li>
								</ul>
							</div>
						</div>

						<div class="col-lg-8 col-md-8 col-sm-10 col-xs-12">
							<div class="reservation_form">
								<form action="" method="POST">
                                    {% csrf_token %}
									<div class="row">
                                        <div class="col-lg-5 col-md-12 col-sm-12 col-xs-12">
											<div class="form_item" data-aos="fade-up" data-aos-delay="100">
                                                 <p>
                                                    <label class="input_title" for="id_location">Pickup Location</label>
                                                     <div class="position-relative">
                                                        <select name="location" required id="id_location">
                                                            <option value="Tirana_international_airport">Tirana International Airport</option>
                                                            <option value="Tirana_city_center">Tirana City Centre</option>
                                                            <option value="Durres_port">Durres Sea Port</option>
                                                        </select>
                                                    </div>
                                                </p>
                                            </div>
                                        </div>

                                        <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                                            <div class="form_item" data-aos="fade-up" data-aos-delay="200">
                                                <p>
                                                    <label class="input_title" for="id_pickup_date">Pickup Date</label>
                                                    <input type="datetime-local" name="pickup_date" required id="id_pickup_date">
                                                </p>
                                            </div>
                                        </div>

                                        <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                                            <div class="form_item" data-aos="fade-up" data-aos-delay="200">
                                                <p>
                                                    <label class="input_title" for="id_return_date">Return Date</label>
                                                    <input type="datetime-local" name="return_date" required id="id_return_date">
                                                </p>
                                            </div>
                                        </div>
									</div>

									<div class="reservation_customer_details">

										<hr data-aos="fade-up" data-aos-delay="200">

										<div class="row align-items-center justify-content-lg-between">
											<div class="col-lg-6 col-md-12 col-sm-12 col-xs-12" data-aos="fade-up" data-aos-delay="300">
												<button type="submit" class="custom_btn bg_default_red text-uppercase">Book Now <img src="{% static 'assets/images/icons/icon_01.png' %}" alt="icon_not_found"></button>
											</div>
										</div>
									</div>
								</form>
							</div>
						</div>

					</div>
				</div>
{#                <div>#}
{#                    <form action="" method="POST">#}
{#                        {{ form.as_p }}#}
{#                        {% csrf_token %}#}
{#                        <button type="submit">Book this car</button>#}
{#                    </form>#}
{#                </div>#}
			</section>
			<!-- reservation_section - end
			================================================== -->


		</main>
		<!-- main body - end
		================================================== -->

    {% endblock content %}

	</body>
</html>